### ISSUE TITLE
How did you create the phoneme sound files?

### ISSUE THREAD

**Issue by Zireael07** [radiohound/TeensyTalk#1]
(I understand from the forums that espeak-ng was involved, but did you mine their binary data format, or just capture and slice the output?)

**Comment by radiohound** [comment]
ESpeak-NG (https://github.com/espeak-ng/espeak-ng) used to create the sound files. You can export these to many different types of sound files. Then I spent a LOT of time cutting the sound files to try to just include the portion needed for the sound. See https://github.com/radiohound/TeensyTalk/blob/main/Phoneme_Conversion_Table_v2.pdf for a little more info on this.

**Comment by christincha** [comment]
Is that okay to generate audio if I only have some phonemes but don't have any stressing information?

**Comment by radiohound** [comment]
christincha, I am not sure I understand your question. But of course, one could stitch together these phonemes to create their own words. Unlike some other phoneme speaking software/devices, I have not implemented any stressing info. For me, this didn't seem to be an issue. Though it's definitely not as refined as espeak on a PC, the code is much, much smaller and the speech seems pretty understandable in the majority of cases. Specific words for your projects could be pieced together to ensure they are spoken correctly. 

I find the speech to be clearer than the SAM device, which tries to utilize stressing info to speak words. This is probably due to the compression used, and lesser quality output audio from the SAM chip.
